IF NOT EXISTS (SELECT *FROM sys.databases 
 WHERE [name] = 'POP3')
BEGIN 
      CREATE DATABASE POP3
END 
GO

USE POP3;
GO


ALTER TABLE Zavod1 ADD CONSTRAINT PK_Zavod PRIMARY KEY (inn);
ALTER TABLE Zakazchik1 ADD CONSTRAINT PK_Zakazchik PRIMARY KEY (nomer_pasporta);
ALTER TABLE Tovar1 ADD CONSTRAINT PK_Tovar PRIMARY KEY (nomer_tovara);
ALTER TABLE Zakaz1 ADD  CONSTRAINT PK_Zakaz PRIMARY KEY (id_zakaza);
ALTER TABLE Otgruzka1 ADD CONSTRAINT PK_Otgruzka PRIMARY KEY (nomer_otgruzki);
ALTER TABLE Kurer1 ADD CONSTRAINT PK_Kurer PRIMARY KEY (nomer_pasporta);