IF NOT EXISTS (SELECT *FROM sys.databases 
 WHERE [name] = 'POP3')
BEGIN 
      CREATE DATABASE POP3
END 
GO

USE POP3;
GO

ALTER TABLE Kurer NOCHECK CONSTRAINT ALL;
ALTER TABLE Otgruzka NOCHECK CONSTRAINT ALL;
ALTER TABLE Zakaz NOCHECK CONSTRAINT ALL;
ALTER TABLE Zakazchik NOCHECK CONSTRAINT ALL;
ALTER TABLE Tovar NOCHECK CONSTRAINT ALL;
ALTER TABLE Zavod NOCHECK CONSTRAINT ALL;

DROP TABLE IF EXISTS Kurer;
DROP TABLE IF EXISTS Otgruzka;    
DROP TABLE IF EXISTS Zakaz;
DROP TABLE IF EXISTS Zakazchik;
DROP TABLE IF EXISTS Tovar;
DROP TABLE IF EXISTS Zavod;

DROP TABLE IF EXISTS Kurer1;
DROP TABLE IF EXISTS Otgruzka1;    
DROP TABLE IF EXISTS Zakaz1;
DROP TABLE IF EXISTS Zakazchik1;
DROP TABLE IF EXISTS Tovar1;
DROP TABLE IF EXISTS Zavod1;